// Ejemplo de uso con la distribución de Scrabble en catalán
const distribucionScrabbleCatala = {
    A: { cantidad: 12, valor: 1 },
    B: { cantidad: 2, valor: 3 },
    C: { cantidad: 3, valor: 2 },
    Ç: { cantidad: 1, valor: 10 },
    D: { cantidad: 3, valor: 2 },
    E: { cantidad: 13, valor: 1 },
    F: { cantidad: 1, valor: 4 },
    G: { cantidad: 2, valor: 3 },
    H: { cantidad: 1, valor: 8 },
    I: { cantidad: 8, valor: 1 },
    J: { cantidad: 1, valor: 8 },
    L: { cantidad: 4, valor: 1 },
    "L·L": { cantidad: 1, valor: 10 },
    M: { cantidad: 3, valor: 2 },
    N: { cantidad: 6, valor: 1 },
    NY: { cantidad: 1, valor: 10 },
    O: { cantidad: 5, valor: 1 },
    P: { cantidad: 2, valor: 3 },
    Qu: { cantidad: 1, valor: 8 },
    R: { cantidad: 8, valor: 1 },
    S: { cantidad: 8, valor: 1 },
    T: { cantidad: 5, valor: 1 },
    U: { cantidad: 4, valor: 1 },
    V: { cantidad: 1, valor: 4 },
    X: { cantidad: 1, valor: 10 },
    Z: { cantidad: 1, valor: 8 },
    "?": { cantidad: 2, valor: 0 },
  };